misconfigurations:
- id: AVD-DS-0011
  # paths:
  # - "/home/vscode/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible/galaxy/data/apb/Dockerfile.j2"
  statement: This Dockerfile.j2 file is installed with pipx.
- id: AVD-DS-0026
  # paths:
  # - Dockerfile
  statement: Accepted risk. There are no healthchecks for dev containers.
