#!/usr/bin/bash -e

# Make the user's bash completion directory
mkdir -p ~/.local/share/bash-completion/completions

# List of commands to loop through
for cmd in argocd cilium cmctl helm kubectl kustomize virtctl
do
    # Make sure the command exists
    if [ -x ~/.local/bin/"${cmd}" ]
    then
        echo "${cmd}: updating bash completions"
        # Create a bash completion file
        ~/.local/bin/"${cmd}" completion bash > ~/.local/share/bash-completion/completions/"${cmd}"
    fi
done

# Commands that generate the bash completion a different way
if [ -x ~/.local/bin/tofu ]
then
    ~/.local/bin/tofu -install-autocomplete
fi

echo "Bash completions updated."
echo "To enable them, run: "
echo "  source ~/.bashrc"
