name: Build Container
run-name: Container build
on:
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
env:
  REGISTRY: quay.io
  IMAGE_REPOSITORY: cyclops-k8s
  IMAGE_NAME: ansible-kubernetes-devcontainer
jobs:
  build-and-push-image:
    runs-on:
      group: Default
    permissions:
      attestations: write
      contents: read
      id-token: write
      security-events: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to the Container registry
        if: |
          (github.event_name == 'push' &&
           github.ref == 'refs/heads/main') ||
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch'
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ${{ env.REGISTRY }}
          password: ${{ secrets.QUAY_TOKEN }}
          username: ${{ secrets.QUAY_USER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      # - name: Setup node
      #   uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      #   with:
      #     node-version: latest

      - name: Build image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Save image to tarball
        run: |
          docker image save ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest -o ${{ github.workspace }}/image.tar

      - name: Generate Trivy json report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: 0
          format: json
          hide-progress: true
          ignore-unfixed: true
          input: ${{ github.workspace }}/image.tar
          list-all-pkgs: true
          output: ${{ github.workspace }}/trivy-report.json
          scanners: vuln,secret,config,license
          trivyignores: .trivyignore

      - name: Upload Trivy JSON report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: trivy-report-json
          path: ${{ github.workspace }}/trivy-report.json
          retention-days: 30

      - name: Download Trivy HTML template
        run: |
          mkdir -p $HOME/.local/bin/trivy-bin/contrib
          curl -L https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o ${{ github.workspace }}/trivy-html.tpl

      - name: Generate Trivy HTML report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: 0
          format: template
          hide-progress: true
          ignore-unfixed: true
          input: ${{ github.workspace }}/image.tar
          list-all-pkgs: true
          output: ${{ github.workspace }}/trivy-report.html
          scanners: vuln,config
          skip-setup-trivy: true
          template: "@${{ github.workspace }}/trivy-html.tpl"
          trivyignores: .trivyignore

      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: trivy-report-html
          path: ${{ github.workspace }}/trivy-report.html
          retention-days: 30

      - name: Generate Trivy table report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: 0
          format: table
          hide-progress: true
          ignore-unfixed: true
          input: ${{ github.workspace }}/image.tar
          list-all-pkgs: true
          output: ${{ github.workspace }}/trivy-report.txt
          scanners: vuln,secret,config,license
          skip-setup-trivy: true
          trivyignores: .trivyignore

      - name: Scan image with Trivy
        id: trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: 1
          format: table
          hide-progress: true
          ignore-unfixed: true
          input: ${{ github.workspace }}/image.tar
          list-all-pkgs: true
          scanners: vuln,secret,config,license
          severity: CRITICAL
          skip-setup-trivy: true
          trivyignores: .trivyignore

      - name: Push image to registry
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
